### ISSUE TITLE
iotileship - PipeSnippetStep

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#358]
Example yaml file
```
name: "test_snippet"
description: "recipe to test prompt messages"
idempotent: True
actions:
  - description: "Test snippet piping"
    name: "PipeSnippetStep"
    context: "iotile hw --port=virtual:simple connect_direct 1 controller"
    commands:
      - "tile_version"
      - "tile_name"
      - "back"
    expect:
      - "[1, 0, 0]"
      - "Simple"
      - 
```
